//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Since Date.
        /// </summary>
        internal static string ActiveSinceDate {
            get {
                return ResourceManager.GetString("ActiveSinceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar-SA.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        internal static string ASC {
            get {
                return ResourceManager.GetString("ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number.
        /// </summary>
        internal static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number 2.
        /// </summary>
        internal static string BankAccountNumber2 {
            get {
                return ResourceManager.GetString("BankAccountNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number 3.
        /// </summary>
        internal static string BankAccountNumber3 {
            get {
                return ResourceManager.GetString("BankAccountNumber3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number 4.
        /// </summary>
        internal static string BankAccountNumber4 {
            get {
                return ResourceManager.GetString("BankAccountNumber4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        internal static string BankFormTitle {
            get {
                return ResourceManager.GetString("BankFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        internal static string BankPageTitle {
            get {
                return ResourceManager.GetString("BankPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill no.
        /// </summary>
        internal static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Details.
        /// </summary>
        internal static string BrandFormTitle {
            get {
                return ResourceManager.GetString("BrandFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        internal static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string BrandPageTitle {
            get {
                return ResourceManager.GetString("BrandPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string btnExportToExcel {
            get {
                return ResourceManager.GetString("btnExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Password.
        /// </summary>
        internal static string btnHidePassword {
            get {
                return ResourceManager.GetString("btnHidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string btnInsert {
            get {
                return ResourceManager.GetString("btnInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        internal static string btnSaveAndContinue {
            get {
                return ResourceManager.GetString("btnSaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; New.
        /// </summary>
        internal static string btnSaveAndNew {
            get {
                return ResourceManager.GetString("btnSaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Print.
        /// </summary>
        internal static string btnSaveAndPrint {
            get {
                return ResourceManager.GetString("btnSaveAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        internal static string btnShowPassword {
            get {
                return ResourceManager.GetString("btnShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string btnVerify {
            get {
                return ResourceManager.GetString("btnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Date.
        /// </summary>
        internal static string CallingDate {
            get {
                return ResourceManager.GetString("CallingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Details.
        /// </summary>
        internal static string CallingFormTitle {
            get {
                return ResourceManager.GetString("CallingFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Name.
        /// </summary>
        internal static string CallingName {
            get {
                return ResourceManager.GetString("CallingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling.
        /// </summary>
        internal static string CallingPageTitle {
            get {
                return ResourceManager.GetString("CallingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePasswordPageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ChequeAmount {
            get {
                return ResourceManager.GetString("ChequeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Date.
        /// </summary>
        internal static string ChequeDate {
            get {
                return ResourceManager.GetString("ChequeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cheques.
        /// </summary>
        internal static string ChequeMultiplePageTitle {
            get {
                return ResourceManager.GetString("ChequeMultiplePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Name.
        /// </summary>
        internal static string ChequeName {
            get {
                return ResourceManager.GetString("ChequeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        internal static string ChequeNo {
            get {
                return ResourceManager.GetString("ChequeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Cheques.
        /// </summary>
        internal static string ChequePageTitle {
            get {
                return ResourceManager.GetString("ChequePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ChequeStatus {
            get {
                return ResourceManager.GetString("ChequeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Status Details.
        /// </summary>
        internal static string ChequeStatusFormTitle {
            get {
                return ResourceManager.GetString("ChequeStatusFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Status Name.
        /// </summary>
        internal static string ChequeStatusName {
            get {
                return ResourceManager.GetString("ChequeStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Status.
        /// </summary>
        internal static string ChequeStatusPageTitle {
            get {
                return ResourceManager.GetString("ChequeStatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Of Residence.
        /// </summary>
        internal static string CityOfResidence {
            get {
                return ResourceManager.GetString("CityOfResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Details.
        /// </summary>
        internal static string ColorFormTitle {
            get {
                return ResourceManager.GetString("ColorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Name.
        /// </summary>
        internal static string ColorName {
            get {
                return ResourceManager.GetString("ColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string ColorPageTitle {
            get {
                return ResourceManager.GetString("ColorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        internal static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        internal static string CompanyFormTitle {
            get {
                return ResourceManager.GetString("CompanyFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyPageTitle {
            get {
                return ResourceManager.GetString("CompanyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Confirm Password.
        /// </summary>
        internal static string ConfirmPasswordCv {
            get {
                return ResourceManager.GetString("ConfirmPasswordCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1.
        /// </summary>
        internal static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2.
        /// </summary>
        internal static string Contact2 {
            get {
                return ResourceManager.GetString("Contact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Any Time.
        /// </summary>
        internal static string ContactAnyTime {
            get {
                return ResourceManager.GetString("ContactAnyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact From Time.
        /// </summary>
        internal static string ContactFromTime {
            get {
                return ResourceManager.GetString("ContactFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Email.
        /// </summary>
        internal static string ContactPersonEmail {
            get {
                return ResourceManager.GetString("ContactPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name.
        /// </summary>
        internal static string ContactPersonName {
            get {
                return ResourceManager.GetString("ContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name 1.
        /// </summary>
        internal static string ContactPersonName1 {
            get {
                return ResourceManager.GetString("ContactPersonName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name 2.
        /// </summary>
        internal static string ContactPersonName2 {
            get {
                return ResourceManager.GetString("ContactPersonName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Phone.
        /// </summary>
        internal static string ContactPersonPhone {
            get {
                return ResourceManager.GetString("ContactPersonPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact To Time.
        /// </summary>
        internal static string ContactToTime {
            get {
                return ResourceManager.GetString("ContactToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Amount.
        /// </summary>
        internal static string ContractAmount {
            get {
                return ResourceManager.GetString("ContractAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Amount Report.
        /// </summary>
        internal static string ContractAmountReportFormTitle {
            get {
                return ResourceManager.GetString("ContractAmountReportFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Contract Amount.
        /// </summary>
        internal static string ContractAmountTotal {
            get {
                return ResourceManager.GetString("ContractAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        internal static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract From Date.
        /// </summary>
        internal static string ContractDateFrom {
            get {
                return ResourceManager.GetString("ContractDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract To Date.
        /// </summary>
        internal static string ContractDateTo {
            get {
                return ResourceManager.GetString("ContractDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amount Report.
        /// </summary>
        internal static string ContractDueReportFormTitle {
            get {
                return ResourceManager.GetString("ContractDueReportFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string ContractEndDate {
            get {
                return ResourceManager.GetString("ContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Details.
        /// </summary>
        internal static string ContractFormTitle {
            get {
                return ResourceManager.GetString("ContractFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Installment Details.
        /// </summary>
        internal static string ContractInstallmentAddEditTitle {
            get {
                return ResourceManager.GetString("ContractInstallmentAddEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Installments.
        /// </summary>
        internal static string ContractInstallmentPageTitle {
            get {
                return ResourceManager.GetString("ContractInstallmentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Installment Report.
        /// </summary>
        internal static string ContractInstallmentReportPageTitle {
            get {
                return ResourceManager.GetString("ContractInstallmentReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string ContractListTitle {
            get {
                return ResourceManager.GetString("ContractListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Master.
        /// </summary>
        internal static string ContractMaster {
            get {
                return ResourceManager.GetString("ContractMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string ContractPageTitle {
            get {
                return ResourceManager.GetString("ContractPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Report.
        /// </summary>
        internal static string ContractReportFormTitle {
            get {
                return ResourceManager.GetString("ContractReportFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start Date.
        /// </summary>
        internal static string ContractStartDate {
            get {
                return ResourceManager.GetString("ContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Status.
        /// </summary>
        internal static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Status Details.
        /// </summary>
        internal static string ContractStatusFormTitle {
            get {
                return ResourceManager.GetString("ContractStatusFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Statuses.
        /// </summary>
        internal static string ContractStatusPageTitle {
            get {
                return ResourceManager.GetString("ContractStatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Title.
        /// </summary>
        internal static string ContractTitle {
            get {
                return ResourceManager.GetString("ContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Write Date.
        /// </summary>
        internal static string ContractWriteDate {
            get {
                return ResourceManager.GetString("ContractWriteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quantity.
        /// </summary>
        internal static string CurrentQuantity {
            get {
                return ResourceManager.GetString("CurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection And Followup.
        /// </summary>
        internal static string CustomerFollowupPageTitle {
            get {
                return ResourceManager.GetString("CustomerFollowupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        internal static string CustomerFormTitle {
            get {
                return ResourceManager.GetString("CustomerFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Guarantor Report.
        /// </summary>
        internal static string CustomerGuarantorReportFormTitle {
            get {
                return ResourceManager.GetString("CustomerGuarantorReportFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name/IdNo.
        /// </summary>
        internal static string CustomerIdNo {
            get {
                return ResourceManager.GetString("CustomerIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string CustomerPageTitle {
            get {
                return ResourceManager.GetString("CustomerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment Details.
        /// </summary>
        internal static string CustomerPaymentAddEditTitle {
            get {
                return ResourceManager.GetString("CustomerPaymentAddEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payments.
        /// </summary>
        internal static string CustomerPaymentPageTitle {
            get {
                return ResourceManager.GetString("CustomerPaymentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Report.
        /// </summary>
        internal static string CustomerReportFormTitle {
            get {
                return ResourceManager.GetString("CustomerReportFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company Name.
        /// </summary>
        internal static string cvCompanyName {
            get {
                return ResourceManager.GetString("cvCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image..
        /// </summary>
        internal static string cvImageName {
            get {
                return ResourceManager.GetString("cvImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        internal static string DESC {
            get {
                return ResourceManager.GetString("DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        internal static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Payment.
        /// </summary>
        internal static string DownPayment {
            get {
                return ResourceManager.GetString("DownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amount.
        /// </summary>
        internal static string DueAmount {
            get {
                return ResourceManager.GetString("DueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Installments.
        /// </summary>
        internal static string DueInstallments {
            get {
                return ResourceManager.GetString("DueInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 1.
        /// </summary>
        internal static string Email1 {
            get {
                return ResourceManager.GetString("Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email 1.
        /// </summary>
        internal static string Email1Rev {
            get {
                return ResourceManager.GetString("Email1Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 1.
        /// </summary>
        internal static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email 1.
        /// </summary>
        internal static string Email2Rev {
            get {
                return ResourceManager.GetString("Email2Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email.
        /// </summary>
        internal static string EmailRev {
            get {
                return ResourceManager.GetString("EmailRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En-US.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        internal static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax 1.
        /// </summary>
        internal static string Fax1 {
            get {
                return ResourceManager.GetString("Fax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax 2.
        /// </summary>
        internal static string Fax2 {
            get {
                return ResourceManager.GetString("Fax2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        internal static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File No.
        /// </summary>
        internal static string FileNo {
            get {
                return ResourceManager.GetString("FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Due Date.
        /// </summary>
        internal static string FilterDueDate {
            get {
                return ResourceManager.GetString("FilterDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        internal static string FormHeader {
            get {
                return ResourceManager.GetString("FormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given To.
        /// </summary>
        internal static string GivenTo {
            get {
                return ResourceManager.GetString("GivenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Amount.
        /// </summary>
        internal static string GrossAmount {
            get {
                return ResourceManager.GetString("GrossAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor.
        /// </summary>
        internal static string Guarantor {
            get {
                return ResourceManager.GetString("Guarantor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor Details.
        /// </summary>
        internal static string GuarantorFormTitle {
            get {
                return ResourceManager.GetString("GuarantorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor Name / Id No.
        /// </summary>
        internal static string GuarantorIdNo {
            get {
                return ResourceManager.GetString("GuarantorIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor Name.
        /// </summary>
        internal static string GuarantorName {
            get {
                return ResourceManager.GetString("GuarantorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantors.
        /// </summary>
        internal static string GuarantorPageTitle {
            get {
                return ResourceManager.GetString("GuarantorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has url?.
        /// </summary>
        internal static string Hasurl {
            get {
                return ResourceManager.GetString("Hasurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id No.
        /// </summary>
        internal static string IdNo {
            get {
                return ResourceManager.GetString("IdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Amount.
        /// </summary>
        internal static string IncomeAmount {
            get {
                return ResourceManager.GetString("IncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income Amount.
        /// </summary>
        internal static string IncomeAmountTotal {
            get {
                return ResourceManager.GetString("IncomeAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        internal static string Installment {
            get {
                return ResourceManager.GetString("Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Amount.
        /// </summary>
        internal static string InstallmentAmount {
            get {
                return ResourceManager.GetString("InstallmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Date.
        /// </summary>
        internal static string InstallmentDate {
            get {
                return ResourceManager.GetString("InstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Skipped.
        /// </summary>
        internal static string InstallmentSkipped {
            get {
                return ResourceManager.GetString("InstallmentSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Start.
        /// </summary>
        internal static string InstallmentStart {
            get {
                return ResourceManager.GetString("InstallmentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Status.
        /// </summary>
        internal static string InstallmentStatus {
            get {
                return ResourceManager.GetString("InstallmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Status Details.
        /// </summary>
        internal static string InstallmentStatusFormTitle {
            get {
                return ResourceManager.GetString("InstallmentStatusFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment Status.
        /// </summary>
        internal static string InstallmentStatusPageTitle {
            get {
                return ResourceManager.GetString("InstallmentStatusPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        internal static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id No.
        /// </summary>
        internal static string InvalidIdNo {
            get {
                return ResourceManager.GetString("InvalidIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number.
        /// </summary>
        internal static string InvalidMobile {
            get {
                return ResourceManager.GetString("InvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Address.
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Based On Month.
        /// </summary>
        internal static string IsBasedOnMonth {
            get {
                return ResourceManager.GetString("IsBasedOnMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Internet Connection.
        /// </summary>
        internal static string IsInternetConnection {
            get {
                return ResourceManager.GetString("IsInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Flag.
        /// </summary>
        internal static string IsRedFlag {
            get {
                return ResourceManager.GetString("IsRedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        internal static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        internal static string ItemFormTitle {
            get {
                return ResourceManager.GetString("ItemFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string ItemPageTitle {
            get {
                return ResourceManager.GetString("ItemPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Stock Report.
        /// </summary>
        internal static string ItemStockReportPageTitle {
            get {
                return ResourceManager.GetString("ItemStockReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Installments.
        /// </summary>
        internal static string Last3Installments {
            get {
                return ResourceManager.GetString("Last3Installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login Date Time.
        /// </summary>
        internal static string LastLoginDateTime {
            get {
                return ResourceManager.GetString("LastLoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Logout DateTime.
        /// </summary>
        internal static string LastLogoutDateTime {
            get {
                return ResourceManager.GetString("LastLogoutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Paid Amount.
        /// </summary>
        internal static string LastPaidAmount {
            get {
                return ResourceManager.GetString("LastPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Paid Date.
        /// </summary>
        internal static string LastPaidDate {
            get {
                return ResourceManager.GetString("LastPaidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string linktoCustomerMasterId {
            get {
                return ResourceManager.GetString("linktoCustomerMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string linktoItemMasterId {
            get {
                return ResourceManager.GetString("linktoItemMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Image.
        /// </summary>
        internal static string LogoImageName {
            get {
                return ResourceManager.GetString("LogoImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile 1.
        /// </summary>
        internal static string Mobile1 {
            get {
                return ResourceManager.GetString("Mobile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile 2.
        /// </summary>
        internal static string Mobile2 {
            get {
                return ResourceManager.GetString("Mobile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile 3.
        /// </summary>
        internal static string Mobile3 {
            get {
                return ResourceManager.GetString("Mobile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Contracts.
        /// </summary>
        internal static string NoOfContracts {
            get {
                return ResourceManager.GetString("NoOfContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Installments.
        /// </summary>
        internal static string NoOfInstallments {
            get {
                return ResourceManager.GetString("NoOfInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found..
        /// </summary>
        internal static string NoRecordMessage {
            get {
                return ResourceManager.GetString("NoRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        internal static string OpeningQuantity {
            get {
                return ResourceManager.GetString("OpeningQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Date.
        /// </summary>
        internal static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Type.
        /// </summary>
        internal static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os.
        /// </summary>
        internal static string Os {
            get {
                return ResourceManager.GetString("Os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Email.
        /// </summary>
        internal static string OwnerEmail {
            get {
                return ResourceManager.GetString("OwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Owner Email.
        /// </summary>
        internal static string OwnerEmailRev {
            get {
                return ResourceManager.GetString("OwnerEmailRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Phone.
        /// </summary>
        internal static string OwnerPhone {
            get {
                return ResourceManager.GetString("OwnerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        internal static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        internal static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Amount.
        /// </summary>
        internal static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Received Report.
        /// </summary>
        internal static string PaymentReceivedPageTitle {
            get {
                return ResourceManager.GetString("PaymentReceivedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        internal static string PaymentTypeFormTitle {
            get {
                return ResourceManager.GetString("PaymentTypeFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string PaymentTypePageTitle {
            get {
                return ResourceManager.GetString("PaymentTypePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Amount.
        /// </summary>
        internal static string PendingAmount {
            get {
                return ResourceManager.GetString("PendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pending Amount.
        /// </summary>
        internal static string PendingAmountTotal {
            get {
                return ResourceManager.GetString("PendingAmountTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name 1.
        /// </summary>
        internal static string PersonName1 {
            get {
                return ResourceManager.GetString("PersonName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name 2.
        /// </summary>
        internal static string PersonName2 {
            get {
                return ResourceManager.GetString("PersonName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        internal static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        internal static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone/Mobile.
        /// </summary>
        internal static string PhoneMobile {
            get {
                return ResourceManager.GetString("PhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoId Image.
        /// </summary>
        internal static string PhotoIdImageName {
            get {
                return ResourceManager.GetString("PhotoIdImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Of Work.
        /// </summary>
        internal static string PlaceOfWork {
            get {
                return ResourceManager.GetString("PlaceOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAN - Login.
        /// </summary>
        internal static string ProjectLogin {
            get {
                return ResourceManager.GetString("ProjectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan - ArrayBit.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAN.
        /// </summary>
        internal static string ProjectNameSmall {
            get {
                return ResourceManager.GetString("ProjectNameSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        internal static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Details.
        /// </summary>
        internal static string PurchaseFormTitle {
            get {
                return ResourceManager.GetString("PurchaseFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string PurchasePageTitle {
            get {
                return ResourceManager.GetString("PurchasePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Rate.
        /// </summary>
        internal static string PurchaseRate {
            get {
                return ResourceManager.GetString("PurchaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Report.
        /// </summary>
        internal static string PurchaseReportPageTitle {
            get {
                return ResourceManager.GetString("PurchaseReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Report.
        /// </summary>
        internal static string PurchaseSalesTransactionsPageTitle {
            get {
                return ResourceManager.GetString("PurchaseSalesTransactionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt no.
        /// </summary>
        internal static string ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation 1.
        /// </summary>
        internal static string Relation1 {
            get {
                return ResourceManager.GetString("Relation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation 2.
        /// </summary>
        internal static string Relation2 {
            get {
                return ResourceManager.GetString("Relation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Details.
        /// </summary>
        internal static string RoleFormTitle {
            get {
                return ResourceManager.GetString("RoleFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string RolePageTitle {
            get {
                return ResourceManager.GetString("RolePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Rights.
        /// </summary>
        internal static string RoleRightsPageTitle {
            get {
                return ResourceManager.GetString("RoleRightsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Date.
        /// </summary>
        internal static string SalesDate {
            get {
                return ResourceManager.GetString("SalesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Details.
        /// </summary>
        internal static string SalesFormTitle {
            get {
                return ResourceManager.GetString("SalesFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string SalesPageTitle {
            get {
                return ResourceManager.GetString("SalesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rate.
        /// </summary>
        internal static string SalesPrice {
            get {
                return ResourceManager.GetString("SalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rate.
        /// </summary>
        internal static string SalesRate {
            get {
                return ResourceManager.GetString("SalesRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        internal static string SalesReportPageTitle {
            get {
                return ResourceManager.GetString("SalesReportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Sms.
        /// </summary>
        internal static string SendSms {
            get {
                return ResourceManager.GetString("SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId.
        /// </summary>
        internal static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        internal static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Amount.
        /// </summary>
        internal static string SettlementAmount {
            get {
                return ResourceManager.GetString("SettlementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Reason.
        /// </summary>
        internal static string SettlementReason {
            get {
                return ResourceManager.GetString("SettlementReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Zero Value.
        /// </summary>
        internal static string ShowZeroValue {
            get {
                return ResourceManager.GetString("ShowZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        internal static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State1 {
            get {
                return ResourceManager.GetString("State1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Installment Amount.
        /// </summary>
        internal static string TotalInstallmentAmount {
            get {
                return ResourceManager.GetString("TotalInstallmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid.
        /// </summary>
        internal static string TotalPaidAmount {
            get {
                return ResourceManager.GetString("TotalPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        internal static string TracePageTitle {
            get {
                return ResourceManager.GetString("TracePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string TranDate {
            get {
                return ResourceManager.GetString("TranDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Id.
        /// </summary>
        internal static string UniqueId {
            get {
                return ResourceManager.GetString("UniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string UserFormTitle {
            get {
                return ResourceManager.GetString("UserFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLog.
        /// </summary>
        internal static string UserlogPageTitle {
            get {
                return ResourceManager.GetString("UserlogPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UserPageTitle {
            get {
                return ResourceManager.GetString("UserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat (%).
        /// </summary>
        internal static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Amount.
        /// </summary>
        internal static string VatAmount {
            get {
                return ResourceManager.GetString("VatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier.
        /// </summary>
        internal static string VerifiedBy {
            get {
                return ResourceManager.GetString("VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness.
        /// </summary>
        internal static string Witness {
            get {
                return ResourceManager.GetString("Witness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Details.
        /// </summary>
        internal static string WitnessFormTitle {
            get {
                return ResourceManager.GetString("WitnessFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WitnessName / Id No.
        /// </summary>
        internal static string WitnessIdNo {
            get {
                return ResourceManager.GetString("WitnessIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness Name.
        /// </summary>
        internal static string WitnessName {
            get {
                return ResourceManager.GetString("WitnessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witnesses .
        /// </summary>
        internal static string WitnessPageTitle {
            get {
                return ResourceManager.GetString("WitnessPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaah Amount.
        /// </summary>
        internal static string ZakaahAmount {
            get {
                return ResourceManager.GetString("ZakaahAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaah Payments Details.
        /// </summary>
        internal static string ZakaahPaymentAddEditTitle {
            get {
                return ResourceManager.GetString("ZakaahPaymentAddEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaah Payments.
        /// </summary>
        internal static string ZakaahPaymentPageTitle {
            get {
                return ResourceManager.GetString("ZakaahPaymentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
